"""Generated by proto2pydantic from test.proto. DO NOT EDIT."""

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING, Any


if TYPE_CHECKING:
    from datetime import datetime

from pydantic import BaseModel, Field, field_serializer
from pydantic import ConfigDict
from pydantic.alias_generators import to_camel


class TaskStatus(str, Enum):
    """Status of a task."""

    TASK_STATUS_UNSPECIFIED = 'TASK_STATUS_UNSPECIFIED'
    TASK_STATUS_PENDING = 'TASK_STATUS_PENDING'
    TASK_STATUS_RUNNING = 'TASK_STATUS_RUNNING'
    TASK_STATUS_COMPLETED = 'TASK_STATUS_COMPLETED'
    TASK_STATUS_FAILED = 'TASK_STATUS_FAILED'


class Address(BaseModel):
    """Address is a nested message type."""

    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )

    street: str = Field(...)
    city: str = Field(...)
    state: str = ''
    zip_code: str = Field(default='', pattern='^[0-9]{5}(-[0-9]{4})?$')
    country: str = Field(default='', min_length=2, max_length=2)

    def to_proto_json(self) -> dict:
        """Serialize to a ProtoJSON-compatible dict (camelCase keys, no None values)."""
        return self.model_dump(by_alias=True, exclude_none=True)



class User(BaseModel):
    """User exercises field_behavior, buf/validate, nested messages, maps, repeated fields, oneofs, well-known types, and OUTPUT_ONLY."""

    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )

    id: str = Field(default='', exclude=True, description='Server-assigned unique identifier.')
    email: str = Field(..., description="The user's email address.")
    display_name: str = Field(..., min_length=1, max_length=200, description='Display name.')
    age: int = Field(default=0, le=150, description='Age of the user.')
    score: float = Field(default=0.0, le=100, description='Score with floating-point constraints.')
    tags: list[str] | None = Field(default=None, min_length=1, max_length=20, description='Tags with repeated constraints.')
    home_address: Address = Field(default=None, description='Home address (nested message).')
    other_addresses: list[Address] | None = Field(default=None, description='Multiple addresses (repeated message).')
    metadata: dict[str, str] | None = Field(default=None, description='Metadata as a map.')
    extra_data: dict[str, Any] = Field(default=None, description='Arbitrary structured data.')
    created_at: datetime = Field(default=None, exclude=True, description='When the user was created.')
    status: TaskStatus = Field(default=None, description='Current status.')
    profile_url: str = Field(default='', description='Profile URL with URI validation.')
    nickname: str | None = Field(default=None, description='Optional nickname (proto3 optional keyword).')
    username: str = Field(..., description='Username required via buf/validate.')
    contact: str | None = None


    def to_proto_json(self) -> dict:
        """Serialize to a ProtoJSON-compatible dict (camelCase keys, no None values)."""
        return self.model_dump(by_alias=True, exclude_none=True)

    @field_serializer('created_at')
    @classmethod
    def _serialize_timestamp(cls, v: datetime | None, _info: Any) -> str | None:
        """Serialize datetime to RFC 3339 with UTC 'Z' suffix for ProtoJSON."""
        if v is None:
            return None
        return v.strftime('%Y-%m-%dT%H:%M:%S.') + f'{v.microsecond // 1000:03d}' + 'Z'



class CreateUserRequest(BaseModel):
    """CreateUserRequest is a typical RPC request message."""

    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )

    user: User = Field(...)

    def to_proto_json(self) -> dict:
        """Serialize to a ProtoJSON-compatible dict (camelCase keys, no None values)."""
        return self.model_dump(by_alias=True, exclude_none=True)



class CreateUserResponse(BaseModel):
    """CreateUserResponse is a typical RPC response message."""

    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )

    user: User = Field(default=None, exclude=True)

    def to_proto_json(self) -> dict:
        """Serialize to a ProtoJSON-compatible dict (camelCase keys, no None values)."""
        return self.model_dump(by_alias=True, exclude_none=True)




__all__ = [
    'Address',
    'CreateUserRequest',
    'CreateUserResponse',
    'TaskStatus',
    'User',
]


# Rebuild models that use TYPE_CHECKING imports (forward references)
User.model_rebuild()
