"""Generated by proto2pydantic from test.proto. DO NOT EDIT."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from typing import Any

from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    """Status of a task."""

    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class Address(BaseModel):
    """Address is a nested message type."""

    street: str = Field(...)
    city: str = Field(...)
    state: str = ''
    zip_code: str = Field(default='', pattern='^[0-9]{5}(-[0-9]{4})?$')
    country: str = Field(default='', min_length=2, max_length=2)


class User(BaseModel):
    """User exercises field_behavior, buf/validate, nested messages, maps, repeated fields, oneofs, well-known types, and OUTPUT_ONLY."""

    id: str = Field(default='', exclude=True, description='Server-assigned unique identifier.')
    email: str = Field(..., description='The user\'s email address.')
    display_name: str = Field(..., min_length=1, max_length=200, description='Display name.')
    age: int = Field(default=0, le=150, description='Age of the user.')
    score: float = Field(default=0.0, le=100, description='Score with floating-point constraints.')
    tags: list[str] | None = Field(default=None, min_length=1, max_length=20, description='Tags with repeated constraints.')
    home_address: Address = Field(default=None, description='Home address (nested message).')
    other_addresses: list[Address] | None = Field(default=None, description='Multiple addresses (repeated message).')
    metadata: dict[str, str] | None = Field(default=None, description='Metadata as a map.')
    extra_data: dict[str, Any] = Field(default=None, description='Arbitrary structured data.')
    created_at: datetime = Field(default=None, exclude=True, description='When the user was created.')
    status: TaskStatus = Field(default=None, description='Current status.')
    profile_url: str = Field(default='', description='Profile URL with URI validation.')
    nickname: str | None = Field(default=None, description='Optional nickname (proto3 optional keyword).')
    username: str = Field(..., description='Username required via buf/validate.')
    contact: str | str | None = None



class CreateUserRequest(BaseModel):
    """CreateUserRequest is a typical RPC request message."""

    user: User = Field(...)


class CreateUserResponse(BaseModel):
    """CreateUserResponse is a typical RPC response message."""

    user: User = Field(default=None, exclude=True)



__all__ = [
    "TaskStatus",
    "Address",
    "User",
    "CreateUserRequest",
    "CreateUserResponse",
]
